# Site settings
author: Rick Rosetti
title: Rick's Software Engineering Blog
header-img: img/home-bg.png
email: rick.rosetti@gmail.com
copyright_name: Rick Rosetti
description: > # this means to ignore newlines until "baseurl:"
  My journey through the Flatiron School full-stack development program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  RickLearnsToCode

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
